<a href="https://colab.research.google.com/github/felixzhao/STAT501-Assignment/blob/main/notebooks/T5_FZ_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statsmodels.api as sm

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
q2_data_path = "/content/drive/My Drive/Study@NZ/VUW@NZ/STATS 501/assignment/data/q2.csv"
q3_data_path = "/content/drive/My Drive/Study@NZ/VUW@NZ/STATS 501/assignment/data/q3.csv"
q4_data_path = "/content/drive/My Drive/Study@NZ/VUW@NZ/STATS 501/assignment/data/q4.csv"

In [4]:
q2_cols = ["Income", "Support"]
q3_cols = ["HDI", "Interest"]
q4_cols = ["Support", "Interest", "Overall"]

In [8]:

q2_df = pd.read_csv(q2_data_path)[q2_cols]
q3_df = pd.read_csv(q3_data_path)[q3_cols]
q4_df = pd.read_csv(q4_data_path)[q4_cols]

# Question 2

In [14]:
q2_x_col = q2_cols[0]
q2_y_col = q2_cols[1]
print(q2_x_col, q2_y_col)

Income Support


In [15]:
X = q2_df[q2_x_col]
y = q2_df[q2_y_col]

# Add a constant to the independent variable set to represent the Bo (intercept)
X = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X).fit()

# Print the summary statistics of the regression model
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                Support   R-squared:                       0.228
Model:                            OLS   Adj. R-squared:                  0.213
Method:                 Least Squares   F-statistic:                     15.34
Date:                Thu, 31 Aug 2023   Prob (F-statistic):           0.000263
Time:                        09:13:31   Log-Likelihood:                -245.63
No. Observations:                  54   AIC:                             495.3
Df Residuals:                      52   BIC:                             499.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        595.6084     21.655     27.504      0.0

# Question 3

In [12]:
q3_x_col = q3_cols[0]
q3_y_col = q3_cols[1]
print(q3_x_col, q3_y_col)

HDI Interest


In [13]:
X = q3_df[q3_x_col]
y = q3_df[q3_y_col]

# Add a constant to the independent variable set to represent the Bo (intercept)
X = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X).fit()

# Print the summary statistics of the regression model
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:               Interest   R-squared:                       0.672
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     102.3
Date:                Thu, 31 Aug 2023   Prob (F-statistic):           1.09e-13
Time:                        09:12:31   Log-Likelihood:                -248.18
No. Observations:                  52   AIC:                             500.4
Df Residuals:                      50   BIC:                             504.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        915.0384     38.491     23.773      0.0

## Quesiton 4, multiple regression

In [5]:
q4_x_1_col = q4_cols[0]
q4_x_2_col = q4_cols[1]
q4_y_col = q4_cols[2]
print(q4_x_1_col, q4_x_2_col, q4_y_col)

Support Interest Overall


In [9]:
X = q4_df[[q4_x_1_col, q4_x_2_col]]
y = q4_df[q4_y_col]

# Add a constant to the independent variable set to represent the Bo (intercept)
X = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X).fit()

# Print the summary statistics of the regression model
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:                Overall   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.639
Method:                 Least Squares   F-statistic:                     50.47
Date:                Thu, 31 Aug 2023   Prob (F-statistic):           4.36e-13
Time:                        09:06:36   Log-Likelihood:                -278.32
No. Observations:                  57   AIC:                             562.6
Df Residuals:                      54   BIC:                             568.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        735.6360     93.539      7.864      0.0

## Interpretation

The output is a summary of the Ordinary Least Squares (OLS) regression model. Below is an interpretation of some of the key statistics:

### Model Fit:
1. R-squared (0.651): This value suggests that approximately 65.1% of the variation in the dependent variable "Overall" can be explained by the independent variables "Support" and "Interest." This is a relatively good fit, although it means that 34.9% of the variability is not captured by the model.

2. Adj. R-squared (0.639): The adjusted R-squared considers the number of predictors in the model, making it a better measure when comparing models with different numbers of predictors. In this case, it's still fairly close to the R-squared, suggesting the model is relatively robust.

3. Prob (F-statistic) (4.36e-13): The F-statistic tests the null hypothesis that all of the regression coefficients are equal to zero, meaning that the model has no explanatory power. A very low p-value (in this case close to zero) rejects the null hypothesis, implying that the model is useful.

### Coefficients:
1. const (735.6360): This is the intercept term, representing the expected value of "Overall" when both "Support" and "Interest" are zero.

2. Support (0.6544): For every one-unit increase in "Support," "Overall" is expected to increase by 0.6544 units, holding all else constant. The p-value for this variable is 0.022, which is below the common alpha level of 0.05, suggesting that "Support" is statistically significant in predicting "Overall."

3. Interest (-1.1316): For every one-unit increase in "Interest," "Overall" is expected to decrease by 1.1316 units, holding all else constant. The p-value for this variable is very close to zero, which means it is statistically significant.

### Additional Observations:
1. Durbin-Watson (1.984): This test is used to detect the presence of autocorrelation (a relationship between values separated from each other by a given time lag) in the residuals. A value of around 2.0 suggests that there is no autocorrelation.

2. Omnibus and Jarque-Bera (JB): These are tests for the normality of the residuals. The p-values (0.043 and 0.0713) are close to the 0.05 threshold, indicating that the assumption of normally-distributed errors might be slightly violated.

3. Condition Number (1.59e+04): A large condition number may indicate multicollinearity among the predictors. It is advisable to look for ways to address this, perhaps by removing variables or using techniques like ridge regression.

4. Standard Errors and t-values: These are used in constructing the confidence intervals for the coefficients. Higher t-values and lower standard errors suggest greater confidence that the parameter is different from zero.